### PR TITLE
Updated tribe data fields to match old ArkApi ones

### PR DESCRIPTION
**Pull request by Pelayori**

### CODE REVIEW

**Comment by MolluskARK** [comment]
What is the motivation behind this? There are a lot of cases where the new API definitions *could* be modified to match the old ones.

My unsolicited opinion is that it's nice to have all `[Name]Field()` functions in the API headers return an lvalue reference. More consistency, more clarity, and more flexibility. `AShooterPlayerState::MyTribeData` is an `FTribeData`, so return an `FTribeData&`.

Over time, the old ASE API headers became kind of a Frankenstein mishmash of API styles. Modifying individual fields for the sake of matching old API code seems like a step back down that path.

**Comment by MolluskARK** [comment]
I would also be onboard with all the the `Field()` accessor functions returning pointers :). As long as they're returning pointers **to** the field, not the **value of** pointer fields like many ASE API accessors returned. Both consistency and ability to write the field are nice to have.

**Comment by Pelayori** [comment]
Yeah, when dumping headers we tried to return lvalues on fields, so pointer fields return a reference to the pointer, that could still be changed.

The `FTribeData` fields modified return a pointer to the field, so one could still change the value of the field by dereferencing the returned pointer.

**Comment by Pelayori** [comment]
Alright. Closing this in favour of consistency

**Pull request closed without merging**
